export const actionTypes = {
    ADD_CARD: 'ADD_CARD',
    DELETE_CARD: 'DELETE_CARD',
    UPDATE_CARD: 'UPDATE_CARD',
    GET_CARDS: 'GET_CARDS',
    GET_CARD: 'GET_CARD',
    ADD_BUCKET: 'ADD_BUCKET',
    DELETE_BUCKET: 'DELETE_BUCKET',
    UPDATE_BUCKET: 'DELETE_BUCKET',
    GET_BUCKETS: 'GET_BUCKETS',
    GET_BUCKET: 'GET_BUCKET',
}